### ISSUE TITLE
応募完了 & 読み込み中 画面を作成

### ISSUE THREAD

**Issue by gyarudev** [oucrc-org/okayama-univ-fes-2021#101]
@massan1111 にお願いしようと思います！

`pages/quiz/thankyou.vue` を作成して、「応募ありがとうございました」などのメッセージを書いてください

**Comment by smpny7** [comment]
# デザイン
Figmaにあります！
https://www.figma.com/file/d6Volcs7O6hYY3tdrbBQnf/%E5%AD%A6%E7%A5%AD2021?node-id=0%3A1

![done](https://user-images.githubusercontent.com/58544849/139545082-f5316173-09d3-4138-bdbb-aa2124f78734.png)

他のページに「トップに戻る」と「修正する」のボタンがあるから、ぜひコピペしてください

- [トップに戻る](https://github.com/oucrc-org/okayama-univ-fes-2021/blob/main/pages/quiz/index.vue#L55)
- [修正する](https://github.com/oucrc-org/okayama-univ-fes-2021/blob/main/pages/quiz/index.vue#L42)

チェックマークは、Figma 上でチェックマークアイコンを選択して、右下の`Export`で書き出せます

少し難しいかもしれないから、わからないところあったら遠慮なくDiscordかけてきてもらえると！

**Comment by smpny7** [comment]
# callbackページ
`/pages/callback.vue`

**Comment by smpny7** [comment]
よろしくお願いします！！
