### ISSUE TITLE
SNSシェアボタン リンク追加

### ISSUE THREAD

**Issue by smpny7** [oucrc-org/okayama-univ-fes-2021#108]
# 実行箇所
ここ↓
<img width="755" alt="スクリーンショット 2021-10-30 2 07 18" src="https://user-images.githubusercontent.com/58544849/139475211-cedb52af-9abb-45b4-a2a4-4cc9a6b738d3.png">

# すること
ここの「LINE」「Twitter」「LIINE」でシェアボタンを押すと、現在のURLを共有する機能をつける。
「シェアする本文」は「岡山大学祭2021 | 笑顔満祭 岡大祭 〜心機一転しちゃいな祭〜」とかにしよう！

# 実装方法
[このサイト](https://designsupply-web.com/media/programming/2992/)の「aタグでSNSシェアボタンを実装する」をみればOK

# 触るファイル
`components/layouts/Footer.vue`

**Comment by smpny7** [comment]
ここもでした↓
`components/layouts/Navigation.vue`

<img width="382" alt="スクリーンショット 2021-10-31 0 43 22" src="https://user-images.githubusercontent.com/58544849/139539976-010db53c-7051-455a-a78a-badcbe9d86b7.png">

**Comment by gyarudev** [comment]
`:href="'https://oufes.com' + $nuxt.$route.path"` でいけると思います

**Comment by gyarudev** [comment]
```vue
<template>
<div>
<a :href="https://twitter.com/intent/tweet?text=「ツイート本文」&url=' + shareurl + '&related=「ツイッターアカウント名」" target="_blank" rel="nofollow">
</a>
<a :href="http://www.facebook.com/share.php?u=' + shareUrl + '&t=「シェア本文」" target="_blank" rel="nofollow">
</a>
<a :href="http://line.me/R/msg/text/?「シェア本文」' + shareUrl" target="_blank" rel="nofollow">
</a>
</div>
</template>
<script lang="ts">
export default {
  data () {
    return {
      shareUrl: 'https://oufes2021.com' + $nuxt.$route.path,
    }
  }
}
</script>

**Comment by gyarudev** [comment]
#119 で解決
