### ISSUE TITLE
MicroCMS webpでの取得

### ISSUE THREAD

**Issue by smpny7** [oucrc-org/okayama-univ-fes-2021#109]
# 実装するページ
- 部活動・サークル紹介（http://localhost:3000/clubs）
- 部活動・サークル紹介 > 〇〇部（http://localhost:3000/clubs/a2pgikkhm）

# リファレンス
https://blog.microcms.io/microcms-with-image-editing/

**Comment by gyarudev** [comment]
これ、画像をコンポーネント化して

```vue
<picture>
  <!-- WebP用画像 -->
  <source :srcset="src + '?fm=webp'" type="image/webp">
  <!-- 従来画像 -->
  <img src="src">
</picture>
```

にする → 画像全部これに置き換える
っていう認識で合ってます？

**Comment by smpny7** [comment]
おっしゃる通り！

**Comment by AAAR-Salmon** [comment]
特に誰もやってなさそうなのでやりますね
