### ISSUE TITLE
「学長メッセージ」ページ作成

### ISSUE THREAD

**Issue by smpny7** [oucrc-org/okayama-univ-fes-2021#33]

**Comment by smpny7** [comment]
・#34 と一緒に担当お願いします。（デザイン使いまわせるので）
・1ブロックをcomponentsに保存しておくといいかも。
・YouTubeは16:9になるように設定してくれると助かります。（ランディングページのライブYouTubeがそうなっているのでコピペでOK）

**Comment by Wansuko-cmd** [comment]
やります

学長メッセージの内容は直接埋め込む感じですか？

**Comment by smpny7** [comment]
そうやね！MicroCMSとかに保存はしなくてOK！

**Comment by smpny7** [comment]
ごめん，間違えた！
#35 と一緒に担当をお願いします！！！！
