### ISSUE TITLE
「ライブ配信」ページ作成

### ISSUE THREAD

**Issue by smpny7** [oucrc-org/okayama-univ-fes-2021#34]

**Comment by smpny7** [comment]
・完全にランディングページのコピペで大丈夫です。
・ついでにランディングページの分も含め、1つのcomponentsにまとめておいてください。
・余裕があれば、「プロコンサート」は11/7 0:00以降非表示になるようにしてもらえると助かります。

**Comment by Wansuko-cmd** [comment]
校友会団体ステージ企画も使いまわしですか？

**Comment by smpny7** [comment]
そうやね！同じcomponentsでOK！

**Comment by Wansuko-cmd** [comment]
予定とかが違ってきたりするのではないでしょうか？
propsに入れるにしては必要な情報量も多そうですし・・・

**Comment by smpny7** [comment]
そうやね...(笑)
まとめない方向でいこう！！

**Comment by Wansuko-cmd** [comment]
プロコンサート部分はたぶんLAと同じだと思うのでまとめときます！
校友会はまた別口でという形で大丈夫ですか？

**Comment by Wansuko-cmd** [comment]
ライブ配信内は別々なんじゃないんですか？
となってくると、校友会コンポーネントとプロコンサートコンポーネントを用意して、LAでは手動で切り替えるor v-ifで切り替える形の方がよさそう

**Comment by smpny7** [comment]
あー確かにライブ配信は別々やな...
そうやね！
